ALTER TABLE characters ADD COLUMN description TEXT NOT NULL DEFAULT '';
ALTER TABLE characters ADD COLUMN age TEXT NOT NULL DEFAULT '';
ALTER TABLE characters ADD COLUMN gender TEXT NOT NULL DEFAULT '';
ALTER TABLE characters ADD COLUMN race TEXT NOT NULL DEFAULT '';
ALTER TABLE characters ADD COLUMN misc TEXT NOT NULL DEFAULT '';
